# Generated by Django 3.2.5 on 2021-08-08 13:09

import base_models.abstract.avatar
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.manager
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=base_models.abstract.avatar.avatar_upload_to, verbose_name='image')),
                ('name', models.CharField(default='Иван', max_length=256, verbose_name='Имя')),
                ('surname', models.CharField(default='Сусанин', max_length=256, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, default='Осипович', max_length=256, null=True, verbose_name='Отчество')),
                ('date_born', models.DateField(verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], default='М', max_length=1, verbose_name='Пол')),
                ('biography', models.TextField(default='Биография', max_length=4096, verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Жанр', max_length=64, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=base_models.abstract.avatar.avatar_upload_to, verbose_name='image')),
                ('title', models.CharField(default='Приключения Тома Сойера', max_length=64, verbose_name='Название книги')),
                ('description_short', ckeditor_uploader.fields.RichTextUploadingField(default='Краткое описание', max_length=2048, verbose_name='Краткое описание')),
                ('description_long', ckeditor_uploader.fields.RichTextUploadingField(default='Подробное описание', max_length=1000000, verbose_name='Описание книги')),
                ('date', models.DateField(verbose_name='Дата написания книги')),
                ('authors', models.ManyToManyField(to='books.Author', verbose_name='Авторы')),
                ('genres', models.ManyToManyField(to='books.Genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['title', '-date'],
            },
            managers=[
                ('books', django.db.models.manager.Manager()),
            ],
        ),
    ]
